### ISSUE TITLE
basti connect results in error with some node versions while using with npx

### ISSUE THREAD

**Issue by AntonKozachuk** [BohdanPetryshyn/basti#21] opened 2022-12-13 12:19 UTC
Command used:
`AWS_PROFILE=support npx basti connect --rds-instance production-postgres-13 --local-port 5434`

Output:
`TypeError [ERR_PACKAGE_IMPORT_NOT_DEFINED]: Package import specifier "#src/common/debug.js" is not defined in package /Users/antonkozachuk/.npm/_npx/a74823000dc99449/node_modules/basti/dist/package.json imported from /Users/antonkozachuk/.npm/_npx/a74823000dc99449/node_modules/basti/dist/src/cli/run.js
    at throwImportNotDefined (internal/modules/esm/resolve.js:293:9)
    at packageImportsResolve (internal/modules/esm/resolve.js:574:3)
    at moduleResolve (internal/modules/esm/resolve.js:700:21)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:819:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:73:40)
    at link (internal/modules/esm/module_job.js:72:36) {
  code: 'ERR_PACKAGE_IMPORT_NOT_DEFINED'
}`

Screenshot:
<img width="2115" alt="image" src="https://user-images.githubusercontent.com/54616703/207316164-a271c39d-a3f0-48e0-b4c4-e434ddc96637.png">

**Comment by BohdanPetryshyn** [comment] 2022-12-13 13:48
Thank you for reporting this, @AntonKozachuk!

**Comment by BohdanPetryshyn** [comment] 2022-12-16 06:55
Hey @AntonKozachuk, what NodeJS version are you using? Looks like your version doesn't support [Subpath Imports](https://nodejs.org/api/packages.html#subpath-imports)

**Comment by BohdanPetryshyn** [comment] 2022-12-16 07:06
I can reproduce the error on Node v12.22.10. Imports work as expected on Node v16.15.0 and v18.9.0

**Comment by AntonKozachuk** [comment] 2022-12-16 09:33
Hi @BohdanPetryshyn ,
My Node version is `16.15.1`.

**Comment by BohdanPetryshyn** [comment] 2023-04-18 06:14
Looks like older Node versions (<14.0.0) don't play well with [Subpath Imports](https://nodejs.org/api/packages.html#subpath-imports) even though support should have been implemented in v12.20.0. 

Couldn't reproduce the error with Node version >14.0.0 (As well as `16.15.1`, reported by @AntonKozachuk)

I'm closing the issue in favor of https://github.com/BohdanPetryshyn/basti/issues/29 (Add support for older Node versions)

**Closed by BohdanPetryshyn** 2023-04-18 06:14 UTC
Labels: bug
